name: JSON Lint

on: [push, pull_request]

jobs:
  json-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get list of changed files
      id: changed_files
      run: |
        git fetch origin
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt

    - name: Validate JSON files
      id: validate_json
      run: |
        for file in $(cat changed_files.txt); do
          # Check if the file is newly created
          if git diff --diff-filter=A --name-only | grep -q "$file"; then
            echo "Skipping validation for newly created file $file"
            continue
          fi
          if [[ $file == cs2/counterstrikesharp/configs/map-text/*.json ]]; then
            echo "Validating $file"
            jq empty "$file" || { echo "Validation failed for $file"; echo $file >> invalid_files.txt; }
          fi
        done

    - name: Revert invalid JSON files
      if: failure()
      run: |
        if [ -f invalid_files.txt ]; then
          for file in $(cat invalid_files.txt); do
            # Check if the file is newly created
            if git diff --diff-filter=A --name-only | grep -q "$file"; then
              echo "Skipping revert for newly created file $file"
              continue
            fi
            echo "Reverting $file"
            git checkout HEAD~1 -- "$file"
          done
          git commit -m "Revert invalid JSON files"
          git push
        fi
